vertical_laser_frame_topic: 'panning_laser_frame'
map_topic: 'map'
odom_topic: 'odom'
body_topic: 'body_frame'
body_map_aligned_topic: 'body_frame_map_aligned'
body_stabilized_topic: 'base_stabilized'

min_lidar_angle: -3.14159
max_lidar_angle: 3.14159
height_filter_deviation_max: 0.05
